### ISSUE TITLE
Question: Wildcard import issues

### ISSUE THREAD

**Issue by jcarroll2007** [bradfordlemley/create-react-app#1]
Hey @bradfordlemley! First off thanks so much for all of the work you've done on the monorepo support here! It's been a huge help in our projects and I've used much of your code as inspiration. 

I had a question I was hoping you might be able to help me with - but it is a little vague. I'll do my best to describe it clearly. For context - I'm still very naive about a lot of the inner-workings of the scripts found here in this project and how all of the different technologies fit together. I'm slowly starting to grasp it. 

I'm working towards building a project that is hopefully going to be very similar to CRA, but for monorepos (and not react specific necessarily). Obviously there's a lot of new ground to cover though. You can find it here [MonorepoJS](https://github.com/monorepojs/monorepojs) if you're ever interested. :)

Anyway *onto my question*.

**Have you ever seen issues with importing with wildcard imports?** For some reason, my import (see example below) is an object of type `Module` at runtime, but with plain `react-scripts` it's an object. It's interesting because in my project I just changed my scripts dependency from `react-scripts` to `@monorepojs/scripts` (the ones from the project above) and the imports in react-scripts were technically plain JS objects, but with `@monorepo/scripts` they're an instance of a `Module` class. Which breaks some things we were previously doing (e.g. merging the import with another object).

**Example**
```
// constants.js
export const CONSTANT_1 = 1
export const CONSTANT_2 = 2

// index.js
import * as constants from './constants'
console.log(constants)

// What we're doing is

const theme = merge({}, constants, overrides) // but as Modules this fails (it works as plain JS objects)
```
> Note: the import above is within my app - not another package outside of my project in the monorepo.

The log above with `react-scripts` would log `{...}` but with my scripts (from @monorepojs) it would log `Module {...}`.

Unfortunately, I have no idea what would be causing this difference in import behavior. Both scripts are using the same version of babel. Have you seen anything like this before if not, would you maybe know a good place to look into to determine what the issue is?

Example in my specific project.
![image](https://user-images.githubusercontent.com/8485105/49521253-0abebd00-f873-11e8-803e-8020bfd36edd.png)

Thank you so much in advance for any help you can offer!

**Comment by bradfordlemley** [comment]
Hi @jcarroll2007, sorry, I don't know where to point you for that particular issue.  Can you set up a simple project that uses your monorepo tool and demonstrates the issue?

**Comment by jcarroll2007** [comment]
@bradfordlemley thanks for the response! I figured out this seems to be behavior introduced from CRA 1.1.5 to 2.x.x. I still am unsure which feature or technology this change was caused by. So, it seems unrelated to monorepo support and therefore this seems to not be the proper place for the question. 

Thanks anyway for your offer to help. :)
